### ISSUE TITLE
独自データで試すには のドキュメント加筆

### ISSUE THREAD

**Issue by ymhiroki** [aws-samples/opensearch-intelligent-search-jp#2]
サンプルデータではなく、自身で用意したデータを用いて動作させる際の手順を [自身のデータで試すには](https://github.com/aws-samples/opensearch-intelligent-search-jp/blob/main/docs/bring-your-own-data.md#%E8%87%AA%E8%BA%AB%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%81%A7%E8%A9%A6%E3%81%99%E3%81%AB%E3%81%AF) のドキュメントに記載して欲しいです

**Comment by tkyaaida** [comment]
#5 で対応されたため close します。
